### ISSUE TITLE
Defining a conditional step

### ISSUE THREAD

**Issue by leechao** [lexik/LexikWorkflowBundle#19]
Hi, I have an issue defining a conditional step in my workflow.
After my request has been validated by HR department, I'd like to check if the request needs to be validated by a director with a conditional step and if so, go to the step named "validation_director". If the request doesn't need to be validated by a director, just end the process.

My conditional step is defined as below :
```
lexik_workflow:
    processes:
        clearance_request:
            start:  clearance_request_created
            steps:
                ....
                validated_by_HR:
                    label:      "Request validated by Human Resources"
                    model_status:   [ setStatus, AppBundle\Entity\Request::STATUS_VALIDATED_HR ]
                    next_states:
                        check_direct_validation:
                            type: step_or
                            target:
                                validation_director: "resource:needDirectorValidation"
               .......
```

I have then, an error when displaying any page : 
```
InvalidTypeException: Invalid type for path "lexik_workflow.processes.clearance_request.steps.validated_by_HR.next_states.check_director_validation.target". Expected scalar, but got array.
```

Any idea of what's wrong with my workflow definition ? 

Thank you :)
