### ISSUE TITLE
Understanding the workflow

### ISSUE THREAD

**Issue by pavan168** [lexik/LexikWorkflowBundle#2]
Hi, 

I have gone through the Workflow example as it states but find it a little difficult to understand some sections. Would you be able to guide me through the following?
1. Are 'roles' defined in each step necessary or is it an additional step? (Are these attributes defined in the library?)
2. In 'model_status' attribute, for an example, 'Project\Bundle\SuperBundle\Entity\Post::STATUS_VALIDATED' where can i find this template entity in the given example? Is this like an object to store the statuses?
3. Along with these defined steps and processes, how would i show the UI? E.g. In 'draft_created' step i want to show a UI and in 'validated_by_admin' step i want to show another. Likewise i would need to show different UIs for each step. Is this possible?
4. Where does this part go to 'service id=project.workflow.listener.post_publication /service'

Thank you in advance.

**Comment by Mentos93** [comment]
@cedric-g Can we please reopen this issue? I also got the errors that table 'lexik_workflow_model_state' doesn't exist, so I created the database table and I also created a column in my order table for status. Because it just make sense to add them to the database.

I've followed everything in the documentation and what you have mentioned in this discussion. But know I'm not sure what to do next.

I've created my `OrderModel` class;

```
namespace Qi\Bss\FrontendBundle\PmodWorkflow\Model;

use Lexik\Bundle\WorkflowBundle\Model\ModelInterface;
use Qi\Bss\BaseBundle\Entity\Business\PurchaseModule\PmodOrder;

class OrderModel implements ModelInterface
{
    private $order;

    public function __construct(PmodOrder $order)
    {
        $this->order = $order;
    }

    public function getPost()
    {
        return $this->order;
    }

    public function setStatus($status)
    {
        $this->order->setStatus($status);
    }

    public function getStatus()
    {
        return $this->order->getStatus();
    }

    /**
     * Returns an unique identifier.
     *
     * @return mixed
     */
    public function getWorkflowIdentifier()
    {
        return md5(get_class($this->order).'-'.$this->order->getId());
    }

    /**
     * Returns data to store in the ModelState.
     *
     * @return array
     */
    public function getWorkflowData()
    {
        return array(
            'order_id' => $this->order->getId(),
            'content' => $this->order->getContent(),
            // ...
        );
    }

    /**
     * Returns the final object.
     * If your entity implements ModelInterface itself just return $this.
     *
     * @return object
     */
    public function getWorkflowObject()
    {
        return $this->order;
    }
}
```
As well as my `OrderPublicationProcessSubscriber` class;

```
namespace Qi\Bss\FrontendBundle\PmodWorkflow\Listener;

use Lexik\Bundle\WorkflowBundle\Event\StepEvent;
use Lexik\Bundle\WorkflowBundle\Event\ValidateStepEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class OrderPublicationProcessSubscriber implements EventSubscriberInterface
{
    /**
     * {@inheritDoc}
     */
    public static function getSubscribedEvents()
    {
        return array(
            'pmod_order_publication.published.validate' => array(
                'handleAccessValidationPublished',
            ),
            'pmod_order_publication.published.validation_fail' => array(
                'handleValidationFail',
            ),
        );
    }

    public function handleAccessValidationPublished(ValidateStepEvent $event)
    {
        if (!$event->getModel()->canBePublished()) {
            $event->addViolation('error message');
        }
    }

    public function handleValidationFail(StepEvent $event)
    {
        // ...
    }
}
```
I've added the service to my `services.yml`;

```
    bss.pmod.workflow.listener.order_publication:
        class: Qi\Bss\FrontendBundle\PmodWorkflow\Listener\OrderPublicationProcessSubscriber
        tags:
            - { name: kernel.event_subscriber }
```
And here is my configurations in my `config.yml`;

```
lexik_workflow:
    processes:
        pmod_order_publication:
            start: draft_created
            end:   [ deleted ]
            steps:
                draft_created:
                    label: "Draft created"
                    roles: [ ROLE_USER ]
                    model_status: [ setStatus, Qi\Bss\BaseBundle\Entity\Business\PurchaseModule\PmodOrder::STATUS_DRAFT ]
                    next_states:
                        validate: { type: step, target: validated_by_admin }

                validated_by_admin:
                    label: "Post validated"
                    roles: [ ROLE_ADMIN ]
                    model_status: [ setStatus, Qi\Bss\BaseBundle\Entity\Business\PurchaseModule\PmodOrder::STATUS_VALIDATED ]
                    next_states:
                        publish: { target: published }

                published:
                    label: "Post published"
                    roles: [ ROLE_USER ]
                    model_status: [ setStatus, Qi\Bss\BaseBundle\Entity\Business\PurchaseModule\PmodOrder::STATUS_PUBLISHED ]
                    on_invalid: draft_created # will try to reach the "draft_created" step in case validations to reach "published" fail.
                    next_states:
                        unpublish: { target: unpublished }

                unpublished:
                    label: "Post unpublished"
                    roles: [ ROLE_USER ]
                    model_status: [ setStatus, Qi\Bss\BaseBundle\Entity\Business\PurchaseModule\PmodOrder::STATUS_UNPUBLISHED ]
                    next_states:
                        delete:  { target: deleted }
                        publish: { target: published }

                deleted:
                    label: "Post deleted"
                    roles: [ ROLE_ADMIN ]
                    model_status: [ setStatus, Qi\Bss\BaseBundle\Entity\Business\PurchaseModule\PmodOrder::STATUS_DELETED ]
                    next_states: ~
```

This is my `PmodOrder` class for in case;

```
class PmodOrder
{
    const STATUS_DRAFT       = 1;
    const STATUS_PUBLISHED   = 2;
    const STATUS_UNPUBLISHED = 3;
    const STATUS_VALIDATED   = 4;
    const STATUS_DELETED     = 5;

    /**
     * @ORM\Column(name="workflow_status", type="string", length=255, nullable=true)
     *
     * @var string
     */
    protected $status;

    //
    // Some other properties for my order
    //
    // Some other getters and setters for my order
    //

    /**
     * Set status
     *
     * @param string $status
     * @return PmodOrder
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string 
     */
    public function getStatus()
    {
        return $this->status;
    }
```

Please, can anyone assist me with what to do next?
Should there be any relation between my `order` table and `lexik_workflow_model_state`? A OneToMany  from `order` sounds logical to me. Or am I wrong?

Thanks in advance!
