### ISSUE TITLE
Use Security Voters instead of roles

### ISSUE THREAD

**Issue by stephanvierkant** [lexik/LexikWorkflowBundle#34]
Having a `roles` attribute is an easy way to check permissions, but has some limitations. What if you want to allow users to edit their own posts/comments/whatever?

I think the [Security Voters](http://symfony.com/doc/current/security/voters.html) are the perfect way to check if a user has permissions to change the state of an object.

What about adding Security Voters to this bundle?

**Comment by cedric-g** [comment]
Hi, you can create your own voter that support a custom attribute, then use this attribute in the step definition. Let's say your voter support the `IS_OWNER` attribute, you can do:

```yml
lexik_workflow:
    processes:
        post_publication:
            # ...
            steps:
                published:
                    label: "Post published"
                    roles: [ IS_OWNER ]
                    # ...
```
